# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.Post', verbose_name='Пост'),
            preserve_default=False,
        ),
    ]
